[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=7D9249A54A2A4F17A7E4B2C39C93F0A1
ProjectName=Call of NARIS
CompanyName=ALNAMI COMPANY
ProjectVersion=0.3.0-master

[/Script/UnrealEd.ProjectPackagingSettings]
; Explicitly cook all user-selectable worlds. Default startup map remains Ashen Forest.
+MapsToCook=(FilePath="/Game/World/Maps/L_AshenForest_VerticalSlice")
+MapsToCook=(FilePath="/Game/World/Maps/L_AshenForest_EntryRestored_V2")
+MapsToCook=(FilePath="/Game/NARIS_AI_Stage/Maps/L_AshenForest_OpenWorld_V4")
+MapsToCook=(FilePath="/Game/World/Maps/L_AshenGate_Playable_V8")
+MapsToCook=(FilePath="/Game/World/Maps/L_AshenGate_QuestPlayable_V9")
